# Generated by Django 3.2.4 on 2021-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('specification', models.CharField(choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('FLUTTER', 'FLUTTER'), ('REACT-N', 'REACT-N'), ('DESKTOP', 'DESKTOP'), ('FULLSTACK', 'FULLSTACK')], default='FRONTEND', max_length=10)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mentor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
