# Generated by Django 3.1.7 on 2021-07-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210714_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
