# Generated by Django 3.1.7 on 2021-07-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210714_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
    ]
